dist: bionic

addons:
  chrome: stable

language: node_js

node_js:
  - "12"

cache:
  yarn: false

before_install:
  - yarn global add codecov

install:
  - yarn install --frozen-lockfile

script:
  - yarn test_lib --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
  - codecov
